/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import java.awt.*;
import java.net.URL;
import javax.swing.*;

/**
 *
 * @author sevhe
 */
public class EnrollmentSystem extends javax.swing.JFrame {

    /**
     * Creates new form EnrollmentSystem
     */
    public EnrollmentSystem() {
        initComponents();
        String mailushere = "<html><a href=\"mailto:mailto:maniagojeng@yahoo.com\"; style=\"color:#ffffff\">jcvhsBucandala@gmail.com</a></html>";
        mailLink.setText(mailushere);
        imageCaller();
    }

    public void imageScale(String link, JLabel label) {
        ImageIcon iconLOGO1 = new ImageIcon("C:/Users/daxxtropezz/Documents/NetBeansProjects/EnrollmentSystem/src/enrollmentsystem" + link);
        Image imgLOGO1 = iconLOGO1.getImage();
        Image imgScaleLOGO1 = imgLOGO1.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconLOGO1 = new ImageIcon(imgScaleLOGO1);
        label.setIcon(scaledIconLOGO1);
    }

    public void imageCaller() {
        String[] link
                = {"/Images/jcvhsHlLogin.jpg",
                    "/Images/newLogo.png",
                    "/Images/LionsRoarASH.png",
                    "/Images/newHeadline.jpg",
                    "/Images/newHeadlineMISSION.jpg",
                    "/Images/newHeadlineVISION.jpg",
                    "/Images/newMap.jpg"};

        imageScale(link[1], logo);
        imageScale(link[1], logoABOUT);
        imageScale(link[1], logoABOUT1);
        imageScale(link[1], logoCONTACTS);
        imageScale(link[1], logoABOUTguideline);
        imageScale(link[3], headLine);
        imageScale(link[4], headLine1);
        imageScale(link[5], headLine2);
        imageScale(link[6], headLine3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanel = new javax.swing.JPanel();
        homeScrollPane = new javax.swing.JScrollPane();
        homePanel = new javax.swing.JPanel();
        missionTEXT = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        visionTEXT = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        headLinetxt1 = new javax.swing.JLabel();
        headLinetxt2 = new javax.swing.JLabel();
        headLine = new javax.swing.JLabel();
        headLine1 = new javax.swing.JLabel();
        headLine2 = new javax.swing.JLabel();
        headLine3 = new javax.swing.JLabel();
        blankLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        menubarHOME = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        aboutLabel = new javax.swing.JLabel();
        contactsLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        spacingLabel = new javax.swing.JLabel();
        signupLabel = new javax.swing.JLabel();
        headTitle = new javax.swing.JLabel();
        headTitleHS = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        AboutUsPanel = new javax.swing.JPanel();
        aboutScrollPane = new javax.swing.JScrollPane();
        aboutPanel = new javax.swing.JPanel();
        descPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        descPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        descPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        descPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        descPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        subTitle17 = new javax.swing.JLabel();
        subTitle18 = new javax.swing.JLabel();
        subTitle16 = new javax.swing.JLabel();
        subTitle15 = new javax.swing.JLabel();
        subTitle14 = new javax.swing.JLabel();
        subTitle11 = new javax.swing.JLabel();
        subTitle12 = new javax.swing.JLabel();
        subTitle13 = new javax.swing.JLabel();
        subTitle8 = new javax.swing.JLabel();
        subTitle9 = new javax.swing.JLabel();
        subTitle10 = new javax.swing.JLabel();
        subTitle5 = new javax.swing.JLabel();
        subTitle6 = new javax.swing.JLabel();
        subTitle7 = new javax.swing.JLabel();
        subTitle1 = new javax.swing.JLabel();
        subTitle1_2 = new javax.swing.JLabel();
        subTitle2 = new javax.swing.JLabel();
        subTitle3 = new javax.swing.JLabel();
        subTitle4 = new javax.swing.JLabel();
        logoABOUTguideline = new javax.swing.JLabel();
        AboutUsTitle3 = new javax.swing.JLabel();
        AboutUsTitle2 = new javax.swing.JLabel();
        desc5 = new javax.swing.JLabel();
        desc4 = new javax.swing.JLabel();
        desc3 = new javax.swing.JLabel();
        desc2 = new javax.swing.JLabel();
        desc1 = new javax.swing.JLabel();
        AboutUsTitle = new javax.swing.JLabel();
        logoABOUT = new javax.swing.JLabel();
        headTitleABOUT1 = new javax.swing.JLabel();
        headTitleABOUT2 = new javax.swing.JLabel();
        logoABOUT1 = new javax.swing.JLabel();
        menubarABOUT = new javax.swing.JPanel();
        spacingLabel3 = new javax.swing.JLabel();
        homeLabel1 = new javax.swing.JLabel();
        aboutLabel1 = new javax.swing.JLabel();
        contactsLabel1 = new javax.swing.JLabel();
        loginLabel1 = new javax.swing.JLabel();
        signupLabel1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        ContactsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fbLink = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mailLink = new javax.swing.JLabel();
        headTitleHS1 = new javax.swing.JLabel();
        logoCONTACTS = new javax.swing.JLabel();
        headTitle1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        menubarHOME1 = new javax.swing.JPanel();
        spacingLabel1 = new javax.swing.JLabel();
        homeLabel2 = new javax.swing.JLabel();
        aboutLabel2 = new javax.swing.JLabel();
        contactsLabel2 = new javax.swing.JLabel();
        loginLabel2 = new javax.swing.JLabel();
        signupLabel2 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(900, 490));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));
        HomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeScrollPane.setBorder(null);

        homePanel.setBackground(new java.awt.Color(140, 0, 1));
        homePanel.setForeground(new java.awt.Color(140, 0, 1));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        missionTEXT.setBackground(new java.awt.Color(140, 0, 1));
        missionTEXT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("MISSION");
        missionTEXT.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("To provide exceptional,");
        missionTEXT.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 440, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("OUR");
        missionTEXT.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 110, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("reasonable, significant,");
        missionTEXT.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 440, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("educational opportunities to all");
        missionTEXT.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 440, -1));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("pupils with emphasis in math,");
        missionTEXT.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 440, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("science, and english.");
        missionTEXT.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 440, -1));

        jLabel47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("To produce morally upright");
        missionTEXT.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 440, -1));

        jLabel48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("and God-fearing pupils.");
        missionTEXT.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 440, -1));

        homePanel.add(missionTEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 460, 260));

        visionTEXT.setBackground(new java.awt.Color(140, 0, 1));
        visionTEXT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("VISION");
        visionTEXT.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 220, -1));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("To produce pupils that will be");
        visionTEXT.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("OUR");
        visionTEXT.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("recognized for excellence in");
        visionTEXT.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, -1));

        jLabel53.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Academics, Leadership, and");
        visionTEXT.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 350, -1));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Moral Righteousness.");
        visionTEXT.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 350, -1));

        homePanel.add(visionTEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 790, 370, 260));

        headLinetxt1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        headLinetxt1.setForeground(new java.awt.Color(255, 255, 255));
        headLinetxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headLinetxt1.setText("WELCOME TO");
        homePanel.add(headLinetxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 40));

        headLinetxt2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        headLinetxt2.setForeground(new java.awt.Color(255, 255, 255));
        headLinetxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headLinetxt2.setText("JOSIAH CHRISTIAN HIGH SCHOOL");
        homePanel.add(headLinetxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 860, 40));
        homePanel.add(headLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 860, 320));
        homePanel.add(headLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 860, 320));
        homePanel.add(headLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 860, 320));
        homePanel.add(headLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1100, 852, 320));

        blankLabel1.setBackground(new java.awt.Color(255, 255, 255));
        blankLabel1.setForeground(new java.awt.Color(140, 0, 1));
        blankLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blankLabel1.setText("|  |  |");
        homePanel.add(blankLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1450, 840, 20));

        homeScrollPane.setViewportView(homePanel);

        HomePanel.add(homeScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 420));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newLogo.png"))); // NOI18N
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        HomePanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 40));

        menubarHOME.setBackground(new java.awt.Color(140, 0, 1));
        menubarHOME.setForeground(new java.awt.Color(140, 0, 1));
        menubarHOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLabel.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(0, 0, 0));
        homeLabel.setText("Home");
        homeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });
        menubarHOME.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        aboutLabel.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setText("About Us");
        aboutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
        });
        menubarHOME.add(aboutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        contactsLabel.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        contactsLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactsLabel.setText("Contacts");
        contactsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsLabelMouseClicked(evt);
            }
        });
        menubarHOME.add(contactsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        loginLabel.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("Login");
        loginLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
        });
        menubarHOME.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        spacingLabel.setForeground(new java.awt.Color(255, 255, 255));
        spacingLabel.setText("|");
        menubarHOME.add(spacingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        signupLabel.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        signupLabel.setForeground(new java.awt.Color(255, 255, 255));
        signupLabel.setText("Sign Up");
        signupLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabelMouseClicked(evt);
            }
        });
        menubarHOME.add(signupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        HomePanel.add(menubarHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 320, 40));

        headTitle.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        headTitle.setForeground(new java.awt.Color(255, 255, 255));
        headTitle.setText("JOSIAH CHRISTIAN");
        HomePanel.add(headTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        headTitleHS.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        headTitleHS.setForeground(new java.awt.Color(255, 255, 255));
        headTitleHS.setText("HIGH SCHOOL");
        HomePanel.add(headTitleHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newBg.jpg"))); // NOI18N
        bg.setText("bg");
        HomePanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        getContentPane().add(HomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));

        AboutUsPanel.setBackground(new java.awt.Color(255, 255, 255));
        AboutUsPanel.setMinimumSize(new java.awt.Dimension(900, 490));
        AboutUsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutScrollPane.setBorder(null);

        aboutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descPanel1.setBackground(new java.awt.Color(140, 0, 1));
        descPanel1.setForeground(new java.awt.Color(140, 0, 1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Since this is home-based, your child's");
        descPanel1.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("learning is pursued in the safety of");
        descPanel1.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("your home. We will not have physical");
        descPanel1.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("nor face-to-face classes, not until");
        descPanel1.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("it is 100% safe and advised by the");
        descPanel1.add(jLabel11);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("government.");
        descPanel1.add(jLabel17);

        aboutPanel.add(descPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 190, 130));

        descPanel2.setBackground(new java.awt.Color(233, 141, 6));
        descPanel2.setForeground(new java.awt.Color(233, 141, 6));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("It is learning done at home using");
        descPanel2.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Josiah LMS(Learning Management");
        descPanel2.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("System) as a platform while being");
        descPanel2.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("facilitated, monitored, and assessed");
        descPanel2.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("by the teacher.");
        descPanel2.add(jLabel16);

        aboutPanel.add(descPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 190, 110));

        descPanel3.setBackground(new java.awt.Color(233, 141, 6));
        descPanel3.setForeground(new java.awt.Color(233, 141, 6));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("No, because this system is teacher-");
        descPanel3.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("facilitated, learning-friendly, easily");
        descPanel3.add(jLabel19);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("accessible, and the students can");
        descPanel3.add(jLabel20);

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("consult their assigned amiable teachers");
        descPanel3.add(jLabel21);

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("at a given schedule. The parents can");
        descPanel3.add(jLabel22);

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("also monitor their child's activities");
        descPanel3.add(jLabel23);

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("and progress anytime.");
        descPanel3.add(jLabel24);

        aboutPanel.add(descPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, 190, 150));

        descPanel4.setBackground(new java.awt.Color(140, 0, 1));
        descPanel4.setForeground(new java.awt.Color(140, 0, 1));

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("This learning system is convenient,");
        descPanel4.add(jLabel25);

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("disruption-free, encourages");
        descPanel4.add(jLabel26);

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("independent learning, improves digital");
        descPanel4.add(jLabel27);

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("literacy, and most importantly, safe,");
        descPanel4.add(jLabel28);

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("preventing your child's exposure to");
        descPanel4.add(jLabel29);

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("covid-19.");
        descPanel4.add(jLabel30);

        aboutPanel.add(descPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 680, 190, 150));

        descPanel5.setBackground(new java.awt.Color(65, 65, 65));
        descPanel5.setForeground(new java.awt.Color(65, 65, 65));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("It is valuable for children to remain");
        descPanel5.add(jLabel31);

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("active and occupied. Based on scientific");
        descPanel5.add(jLabel32);

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("studies it is not good for children to be");
        descPanel5.add(jLabel33);

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("idle for a long period for this can have negative");
        descPanel5.add(jLabel34);

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("implications on their mental,");
        descPanel5.add(jLabel35);

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("social, and physical well-being.");
        descPanel5.add(jLabel36);

        aboutPanel.add(descPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 890, 670, 70));

        subTitle17.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle17.setForeground(new java.awt.Color(255, 255, 255));
        subTitle17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle17.setText("-------");
        aboutPanel.add(subTitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 190, -1));

        subTitle18.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle18.setForeground(new java.awt.Color(255, 255, 255));
        subTitle18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle18.setText("-------");
        aboutPanel.add(subTitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 200, -1));

        subTitle16.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle16.setForeground(new java.awt.Color(255, 255, 255));
        subTitle16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle16.setText("-------");
        aboutPanel.add(subTitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 200, -1));

        subTitle15.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle15.setForeground(new java.awt.Color(255, 255, 255));
        subTitle15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle15.setText("-------");
        aboutPanel.add(subTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 200, -1));

        subTitle14.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle14.setForeground(new java.awt.Color(255, 255, 255));
        subTitle14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle14.setText("WHY ENROLL NOW?");
        aboutPanel.add(subTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 870, 860, -1));

        subTitle11.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle11.setForeground(new java.awt.Color(255, 255, 255));
        subTitle11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle11.setText("PANDEMIC?");
        aboutPanel.add(subTitle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 210, 40));

        subTitle12.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle12.setForeground(new java.awt.Color(255, 255, 255));
        subTitle12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle12.setText("PARENTS?");
        aboutPanel.add(subTitle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 210, 40));

        subTitle13.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle13.setForeground(new java.awt.Color(255, 255, 255));
        subTitle13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle13.setText("TO THE TRADITIONAL LEARNING?");
        aboutPanel.add(subTitle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 210, 40));

        subTitle8.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle8.setForeground(new java.awt.Color(255, 255, 255));
        subTitle8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle8.setText("CHILDREN DURING THIS");
        aboutPanel.add(subTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 210, 40));

        subTitle9.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle9.setForeground(new java.awt.Color(255, 255, 255));
        subTitle9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle9.setText("ADDED BURDEN TO THE");
        aboutPanel.add(subTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 210, 40));

        subTitle10.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle10.setForeground(new java.awt.Color(255, 255, 255));
        subTitle10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle10.setText("LEARNING SYSTEM COMPARED");
        aboutPanel.add(subTitle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, 210, 40));

        subTitle5.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle5.setForeground(new java.awt.Color(255, 255, 255));
        subTitle5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle5.setText("SAFETY OF OUR");
        aboutPanel.add(subTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 210, 40));

        subTitle6.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle6.setForeground(new java.awt.Color(255, 255, 255));
        subTitle6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle6.setText("LEARNING BE AN");
        aboutPanel.add(subTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 210, 40));

        subTitle7.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle7.setForeground(new java.awt.Color(255, 255, 255));
        subTitle7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle7.setText("ADVANTAGE OF THIS HOME-BASED ");
        aboutPanel.add(subTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 210, 40));

        subTitle1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle1.setForeground(new java.awt.Color(255, 255, 255));
        subTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle1.setText("WHAT IS HOME-BASED");
        aboutPanel.add(subTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 210, 20));

        subTitle1_2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle1_2.setForeground(new java.awt.Color(255, 255, 255));
        subTitle1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle1_2.setText("/REMOTE LEARNING? ");
        aboutPanel.add(subTitle1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 210, 40));

        subTitle2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle2.setForeground(new java.awt.Color(255, 255, 255));
        subTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle2.setText("HOW ABOUT THE HEALTH");
        aboutPanel.add(subTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 210, 20));

        subTitle3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle3.setForeground(new java.awt.Color(255, 255, 255));
        subTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle3.setText("WILL THIS MODE OF");
        aboutPanel.add(subTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 210, 20));

        subTitle4.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        subTitle4.setForeground(new java.awt.Color(255, 255, 255));
        subTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle4.setText("WHAT WILL BE THE");
        aboutPanel.add(subTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 210, 20));

        logoABOUTguideline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newLogo.png"))); // NOI18N
        aboutPanel.add(logoABOUTguideline, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 60, 60));

        AboutUsTitle3.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        AboutUsTitle3.setForeground(new java.awt.Color(237, 143, 9));
        AboutUsTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutUsTitle3.setText("GUIDELINES");
        aboutPanel.add(AboutUsTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 230, 90));

        AboutUsTitle2.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        AboutUsTitle2.setForeground(new java.awt.Color(255, 255, 255));
        AboutUsTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutUsTitle2.setText("HOME OF THE RED LIONS:");
        aboutPanel.add(AboutUsTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 360, 90));

        desc5.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        desc5.setForeground(new java.awt.Color(0, 0, 0));
        desc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc5.setText("bringing reform over the education of the youth.");
        aboutPanel.add(desc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 610, -1));

        desc4.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        desc4.setForeground(new java.awt.Color(0, 0, 0));
        desc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc4.setText("Josiah, the Josiah Christian Values High School is confident in");
        aboutPanel.add(desc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 610, -1));

        desc3.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        desc3.setForeground(new java.awt.Color(0, 0, 0));
        desc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc3.setText("and high standards for morality and integrity. Just like King");
        aboutPanel.add(desc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 610, -1));

        desc2.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        desc2.setForeground(new java.awt.Color(0, 0, 0));
        desc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc2.setText("next generation for leadership, real educational achievement,");
        aboutPanel.add(desc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 610, -1));

        desc1.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        desc1.setForeground(new java.awt.Color(0, 0, 0));
        desc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc1.setText("Josiah Christian Values High School is confident in training the");
        aboutPanel.add(desc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 610, -1));

        AboutUsTitle.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        AboutUsTitle.setForeground(new java.awt.Color(255, 255, 255));
        AboutUsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutUsTitle.setText("About Us");
        aboutPanel.add(AboutUsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 101, 820, 90));

        logoABOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newLogo.png"))); // NOI18N
        logoABOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoABOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoABOUTMouseClicked(evt);
            }
        });
        aboutPanel.add(logoABOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 40));

        headTitleABOUT1.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        headTitleABOUT1.setForeground(new java.awt.Color(255, 255, 255));
        headTitleABOUT1.setText("JOSIAH CHRISTIAN");
        aboutPanel.add(headTitleABOUT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        headTitleABOUT2.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        headTitleABOUT2.setForeground(new java.awt.Color(255, 255, 255));
        headTitleABOUT2.setText("HIGH SCHOOL");
        aboutPanel.add(headTitleABOUT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));
        aboutPanel.add(logoABOUT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 250));

        menubarABOUT.setBackground(new java.awt.Color(140, 0, 1));
        menubarABOUT.setForeground(new java.awt.Color(140, 0, 1));
        menubarABOUT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spacingLabel3.setForeground(new java.awt.Color(255, 255, 255));
        spacingLabel3.setText("|");
        menubarABOUT.add(spacingLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        homeLabel1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        homeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel1.setText("Home");
        homeLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabel1MouseClicked(evt);
            }
        });
        menubarABOUT.add(homeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        aboutLabel1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        aboutLabel1.setForeground(new java.awt.Color(0, 0, 0));
        aboutLabel1.setText("About Us");
        aboutLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabel1MouseClicked(evt);
            }
        });
        menubarABOUT.add(aboutLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        contactsLabel1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        contactsLabel1.setForeground(new java.awt.Color(255, 255, 255));
        contactsLabel1.setText("Contacts");
        contactsLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactsLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsLabel1MouseClicked(evt);
            }
        });
        menubarABOUT.add(contactsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        loginLabel1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        loginLabel1.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel1.setText("Login");
        loginLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabel1MouseClicked(evt);
            }
        });
        menubarABOUT.add(loginLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        signupLabel1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        signupLabel1.setForeground(new java.awt.Color(255, 255, 255));
        signupLabel1.setText("Sign Up");
        signupLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabel1MouseClicked(evt);
            }
        });
        menubarABOUT.add(signupLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        aboutPanel.add(menubarABOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 320, 40));

        jLabel37.setBackground(new java.awt.Color(65, 65, 65));
        jLabel37.setForeground(new java.awt.Color(65, 65, 65));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("| | |");
        aboutPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 960, 820, -1));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newBgAbout.jpg"))); // NOI18N
        bg1.setText("bg");
        aboutPanel.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        aboutScrollPane.setViewportView(aboutPanel);

        AboutUsPanel.add(aboutScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));

        getContentPane().add(AboutUsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));

        ContactsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContactsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMAIL US");
        ContactsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 240, 280, -1));

        fbLink.setForeground(new java.awt.Color(0, 0, 0));
        fbLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fbLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/FBLogoSmall.jpg"))); // NOI18N
        fbLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fbLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbLinkMouseClicked(evt);
            }
        });
        ContactsPanel.add(fbLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VISIT US");
        ContactsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 280, -1));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SMART: 0999-889-0345");
        ContactsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, -1));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0920-911-9623");
        ContactsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 200, -1));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GLOBE:     0917-816-8346 ");
        ContactsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 250, -1));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CONTACT US");
        ContactsPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 280, -1));

        mailLink.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailLink.setForeground(new java.awt.Color(255, 255, 255));
        mailLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mailLink.setText("jcvhsBucandala@gmail.com");
        mailLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContactsPanel.add(mailLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 280, 20));

        headTitleHS1.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        headTitleHS1.setForeground(new java.awt.Color(255, 255, 255));
        headTitleHS1.setText("HIGH SCHOOL");
        ContactsPanel.add(headTitleHS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        logoCONTACTS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newLogo.png"))); // NOI18N
        logoCONTACTS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoCONTACTS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoCONTACTSMouseClicked(evt);
            }
        });
        ContactsPanel.add(logoCONTACTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 40));

        headTitle1.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        headTitle1.setForeground(new java.awt.Color(255, 255, 255));
        headTitle1.setText("JOSIAH CHRISTIAN");
        ContactsPanel.add(headTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        jLabel38.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("GET IN TOUCH");
        ContactsPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 820, -1));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("we'd love to hear from you");
        ContactsPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 260, -1));

        menubarHOME1.setBackground(new java.awt.Color(140, 0, 1));
        menubarHOME1.setForeground(new java.awt.Color(140, 0, 1));
        menubarHOME1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spacingLabel1.setForeground(new java.awt.Color(255, 255, 255));
        spacingLabel1.setText("|");
        menubarHOME1.add(spacingLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        homeLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        homeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel2.setText("Home");
        homeLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabel2MouseClicked(evt);
            }
        });
        menubarHOME1.add(homeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        aboutLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        aboutLabel2.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel2.setText("About Us");
        aboutLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabel2MouseClicked(evt);
            }
        });
        menubarHOME1.add(aboutLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        contactsLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        contactsLabel2.setForeground(new java.awt.Color(0, 0, 0));
        contactsLabel2.setText("Contacts");
        contactsLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactsLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsLabel2MouseClicked(evt);
            }
        });
        menubarHOME1.add(contactsLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        loginLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        loginLabel2.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel2.setText("Login");
        loginLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabel2MouseClicked(evt);
            }
        });
        menubarHOME1.add(loginLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        signupLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        signupLabel2.setForeground(new java.awt.Color(255, 255, 255));
        signupLabel2.setText("Sign Up");
        signupLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabel2MouseClicked(evt);
            }
        });
        menubarHOME1.add(signupLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        ContactsPanel.add(menubarHOME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 320, 40));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newBgContacts.jpg"))); // NOI18N
        bg2.setText("bg");
        bg2.setToolTipText("");
        ContactsPanel.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        getContentPane().add(ContactsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        HomePanel.setVisible(true);
        AboutUsPanel.setVisible(false);
        ContactsPanel.setVisible(false);
    }//GEN-LAST:event_homeLabelMouseClicked

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        HomePanel.setVisible(false);
        AboutUsPanel.setVisible(true);
        ContactsPanel.setVisible(false);
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void contactsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsLabelMouseClicked
        HomePanel.setVisible(false);
        AboutUsPanel.setVisible(false);
        ContactsPanel.setVisible(true);
    }//GEN-LAST:event_contactsLabelMouseClicked

    private void homeLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabel1MouseClicked
        HomePanel.setVisible(true);
        AboutUsPanel.setVisible(false);
        ContactsPanel.setVisible(false);
    }//GEN-LAST:event_homeLabel1MouseClicked

    private void aboutLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabel1MouseClicked
        HomePanel.setVisible(false);
        AboutUsPanel.setVisible(true);
        ContactsPanel.setVisible(false);
    }//GEN-LAST:event_aboutLabel1MouseClicked

    private void contactsLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsLabel1MouseClicked
        HomePanel.setVisible(false);
        AboutUsPanel.setVisible(false);
        ContactsPanel.setVisible(true);
    }//GEN-LAST:event_contactsLabel1MouseClicked

    private void homeLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabel2MouseClicked
        HomePanel.setVisible(true);
        AboutUsPanel.setVisible(false);
        ContactsPanel.setVisible(false);
    }//GEN-LAST:event_homeLabel2MouseClicked

    private void aboutLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabel2MouseClicked
        HomePanel.setVisible(false);
        AboutUsPanel.setVisible(true);
        ContactsPanel.setVisible(false);
    }//GEN-LAST:event_aboutLabel2MouseClicked

    private void contactsLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsLabel2MouseClicked
        HomePanel.setVisible(false);
        AboutUsPanel.setVisible(false);
        ContactsPanel.setVisible(true);
    }//GEN-LAST:event_contactsLabel2MouseClicked

    private void fbLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbLinkMouseClicked
        try {
            Desktop.getDesktop().browse(new URL("https://web.facebook.com/JosiahChristianValuesHighSchool/").toURI());
//            fbLink.setForeground(Color.BLUE.darker());
//            fbLink.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_fbLinkMouseClicked

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.loginPanel.setVisible(true);
        lf.registerPanel.setVisible(false);
        lf.setLocationRelativeTo(null);
        lf.setSize(900, 490);
        lf.pack();
    }//GEN-LAST:event_loginLabelMouseClicked

    private void signupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelMouseClicked
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.loginPanel.setVisible(false);
        lf.registerPanel.setVisible(true);
        lf.setLocationRelativeTo(null);
        lf.setSize(900, 490);
        lf.pack();
    }//GEN-LAST:event_signupLabelMouseClicked

    private void loginLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabel1MouseClicked
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.loginPanel.setVisible(true);
        lf.registerPanel.setVisible(false);
        lf.setLocationRelativeTo(null);
        lf.setSize(900, 490);
        lf.pack();
    }//GEN-LAST:event_loginLabel1MouseClicked

    private void signupLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabel1MouseClicked
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.loginPanel.setVisible(false);
        lf.registerPanel.setVisible(true);
        lf.setLocationRelativeTo(null);
        lf.setSize(900, 490);
        lf.pack();
    }//GEN-LAST:event_signupLabel1MouseClicked

    private void loginLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabel2MouseClicked
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.loginPanel.setVisible(true);
        lf.registerPanel.setVisible(false);
        lf.setLocationRelativeTo(null);
        lf.setSize(900, 490);
        lf.pack();
    }//GEN-LAST:event_loginLabel2MouseClicked

    private void signupLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabel2MouseClicked
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.loginPanel.setVisible(false);
        lf.registerPanel.setVisible(true);
        lf.setLocationRelativeTo(null);
        lf.setSize(900, 490);
        lf.pack();
    }//GEN-LAST:event_signupLabel2MouseClicked
    JFrame frame;
    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Enrollment System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_logoMouseClicked

    private void logoABOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoABOUTMouseClicked
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Enrollment System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_logoABOUTMouseClicked

    private void logoCONTACTSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoCONTACTSMouseClicked
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Enrollment System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_logoCONTACTSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                new EnrollmentSystem().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel AboutUsPanel;
    private javax.swing.JLabel AboutUsTitle;
    private javax.swing.JLabel AboutUsTitle2;
    private javax.swing.JLabel AboutUsTitle3;
    public static javax.swing.JPanel ContactsPanel;
    public static javax.swing.JPanel HomePanel;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JLabel aboutLabel1;
    private javax.swing.JLabel aboutLabel2;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JScrollPane aboutScrollPane;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel blankLabel1;
    private javax.swing.JLabel contactsLabel;
    private javax.swing.JLabel contactsLabel1;
    private javax.swing.JLabel contactsLabel2;
    private javax.swing.JLabel desc1;
    private javax.swing.JLabel desc2;
    private javax.swing.JLabel desc3;
    private javax.swing.JLabel desc4;
    private javax.swing.JLabel desc5;
    private javax.swing.JPanel descPanel1;
    private javax.swing.JPanel descPanel2;
    private javax.swing.JPanel descPanel3;
    private javax.swing.JPanel descPanel4;
    private javax.swing.JPanel descPanel5;
    private javax.swing.JLabel fbLink;
    private javax.swing.JLabel headLine;
    private javax.swing.JLabel headLine1;
    private javax.swing.JLabel headLine2;
    private javax.swing.JLabel headLine3;
    private javax.swing.JLabel headLinetxt1;
    private javax.swing.JLabel headLinetxt2;
    private javax.swing.JLabel headTitle;
    private javax.swing.JLabel headTitle1;
    private javax.swing.JLabel headTitleABOUT1;
    private javax.swing.JLabel headTitleABOUT2;
    private javax.swing.JLabel headTitleHS;
    private javax.swing.JLabel headTitleHS1;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel homeLabel1;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JPanel homePanel;
    private javax.swing.JScrollPane homeScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JLabel loginLabel2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoABOUT;
    private javax.swing.JLabel logoABOUT1;
    private javax.swing.JLabel logoABOUTguideline;
    private javax.swing.JLabel logoCONTACTS;
    private javax.swing.JLabel mailLink;
    private javax.swing.JPanel menubarABOUT;
    private javax.swing.JPanel menubarHOME;
    private javax.swing.JPanel menubarHOME1;
    private javax.swing.JPanel missionTEXT;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JLabel signupLabel1;
    private javax.swing.JLabel signupLabel2;
    private javax.swing.JLabel spacingLabel;
    private javax.swing.JLabel spacingLabel1;
    private javax.swing.JLabel spacingLabel3;
    private javax.swing.JLabel subTitle1;
    private javax.swing.JLabel subTitle10;
    private javax.swing.JLabel subTitle11;
    private javax.swing.JLabel subTitle12;
    private javax.swing.JLabel subTitle13;
    private javax.swing.JLabel subTitle14;
    private javax.swing.JLabel subTitle15;
    private javax.swing.JLabel subTitle16;
    private javax.swing.JLabel subTitle17;
    private javax.swing.JLabel subTitle18;
    private javax.swing.JLabel subTitle1_2;
    private javax.swing.JLabel subTitle2;
    private javax.swing.JLabel subTitle3;
    private javax.swing.JLabel subTitle4;
    private javax.swing.JLabel subTitle5;
    private javax.swing.JLabel subTitle6;
    private javax.swing.JLabel subTitle7;
    private javax.swing.JLabel subTitle8;
    private javax.swing.JLabel subTitle9;
    private javax.swing.JPanel visionTEXT;
    // End of variables declaration//GEN-END:variables
}
