/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import java.awt.*;
import java.io.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.*; // uses Level and Logger

/**
 *
 * @author sevhe
 */
public class EnrollmentForm extends javax.swing.JFrame {

    /**
     * Creates new form EnrollmentForm
     */
    private static final String URL = "jdbc:mysql://localhost:3306/enrollmentsystem?allowPublicKeyRetrieval=true&useSSL=false";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "@theHouseof25";

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rset = null;

    public EnrollmentForm() {
        initComponents();
        scalingImg();
        btnEnable();
    }

    public void scalingImg() {
        ImageIcon iconLOGO = new ImageIcon("C:/Users/daxxtropezz/Documents/NetBeansProjects/EnrollmentSystem/src/enrollmentsystem/Images/newLogo.png");
        Image imgLOGO = iconLOGO.getImage();
        Image imgScaleLOGO = imgLOGO.getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconLOGO = new ImageIcon(imgScaleLOGO);
        logo.setIcon(scaledIconLOGO);
    }

    public void btnEnable() {
        String textfield1 = RCtxtfield.getText();
        String textfield2 = F137txtfield.getText();
        String textfield3 = BCtxtfield.getText();
        String textfield4 = GMtxtfield.getText();
        String textfield5 = TORtxtfield.getText();

        if (!"INSERT IMAGE HERE!".equals(textfield1) && !"INSERT IMAGE HERE!".equals(textfield2)
                && !"INSERT IMAGE HERE!".equals(textfield3) && !"INSERT IMAGE HERE!".equals(textfield4)
                && !"INSERT IMAGE HERE!".equals(textfield5)) {
            submitBtn.setEnabled(true);
        } else {
            submitBtn.setEnabled(false);
        }
    }

    public JTextField imgSetScale(JTextField setFile) {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        setFile.setText(filename);
        ImageIcon icon = new ImageIcon(filename);
        Image imgScale = icon.getImage().getScaledInstance(imageDisplay.getWidth(), imageDisplay.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        imageDisplay.setIcon(scaledIcon);

        return setFile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hiddenPRI = new javax.swing.JLabel();
        imgPanel = new javax.swing.JPanel();
        imageDisplay = new javax.swing.JLabel();
        fillUpForm = new javax.swing.JPanel();
        rcText = new javax.swing.JLabel();
        f137Text = new javax.swing.JLabel();
        bcText = new javax.swing.JLabel();
        gmText = new javax.swing.JLabel();
        torText = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        f137Attach = new javax.swing.JButton();
        rcAttach = new javax.swing.JButton();
        gmAttach = new javax.swing.JButton();
        bcAttach = new javax.swing.JButton();
        torAttach = new javax.swing.JButton();
        RCtxtfield = new javax.swing.JTextField();
        F137txtfield = new javax.swing.JTextField();
        BCtxtfield = new javax.swing.JTextField();
        GMtxtfield = new javax.swing.JTextField();
        TORtxtfield = new javax.swing.JTextField();
        headEF1 = new javax.swing.JLabel();
        headEF2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hiddenPRI.setForeground(new java.awt.Color(140, 0, 1));
        getContentPane().add(hiddenPRI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        imgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/imageInsertHere.jpg"))); // NOI18N
        imgPanel.add(imageDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 320));

        getContentPane().add(imgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 250, 340));

        fillUpForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rcText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        rcText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rcText.setText("Report Card: ");
        fillUpForm.add(rcText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        f137Text.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        f137Text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        f137Text.setText("Form 137: ");
        fillUpForm.add(f137Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        bcText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bcText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bcText.setText("Birth Certificate: ");
        fillUpForm.add(bcText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        gmText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        gmText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gmText.setText("Good Moral: ");
        fillUpForm.add(gmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        torText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        torText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        torText.setText("ToR: ");
        fillUpForm.add(torText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        submitBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        fillUpForm.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 430, 40));

        f137Attach.setText("Attach");
        f137Attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f137AttachActionPerformed(evt);
            }
        });
        fillUpForm.add(f137Attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 30));

        rcAttach.setText("Attach");
        rcAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcAttachActionPerformed(evt);
            }
        });
        fillUpForm.add(rcAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, 30));

        gmAttach.setText("Attach");
        gmAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmAttachActionPerformed(evt);
            }
        });
        fillUpForm.add(gmAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, 30));

        bcAttach.setText("Attach");
        bcAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcAttachActionPerformed(evt);
            }
        });
        fillUpForm.add(bcAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 30));

        torAttach.setText("Attach");
        torAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torAttachActionPerformed(evt);
            }
        });
        fillUpForm.add(torAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 30));

        RCtxtfield.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RCtxtfield.setText("INSERT IMAGE HERE!");
        RCtxtfield.setEnabled(false);
        fillUpForm.add(RCtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 310, 30));

        F137txtfield.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        F137txtfield.setText("INSERT IMAGE HERE!");
        F137txtfield.setEnabled(false);
        fillUpForm.add(F137txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 310, 30));

        BCtxtfield.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BCtxtfield.setText("INSERT IMAGE HERE!");
        BCtxtfield.setEnabled(false);
        fillUpForm.add(BCtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 310, 30));

        GMtxtfield.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GMtxtfield.setText("INSERT IMAGE HERE!");
        GMtxtfield.setEnabled(false);
        fillUpForm.add(GMtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 310, 30));

        TORtxtfield.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TORtxtfield.setText("INSERT IMAGE HERE!");
        TORtxtfield.setEnabled(false);
        fillUpForm.add(TORtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 310, 30));

        getContentPane().add(fillUpForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 480, 340));

        headEF1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        headEF1.setForeground(new java.awt.Color(0, 0, 0));
        headEF1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headEF1.setText("Enrollment Form");
        getContentPane().add(headEF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 200, 40));

        headEF2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        headEF2.setForeground(new java.awt.Color(255, 255, 255));
        headEF2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headEF2.setText("Please Fill Up!");
        getContentPane().add(headEF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 160, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newLogo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 40, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newBg.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rcAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcAttachActionPerformed
        imgSetScale(RCtxtfield);
        btnEnable();
    }//GEN-LAST:event_rcAttachActionPerformed

    private void f137AttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f137AttachActionPerformed
        imgSetScale(F137txtfield);
        btnEnable();
    }//GEN-LAST:event_f137AttachActionPerformed

    private void bcAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcAttachActionPerformed
        imgSetScale(BCtxtfield);
        btnEnable();
    }//GEN-LAST:event_bcAttachActionPerformed

    private void gmAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmAttachActionPerformed
        imgSetScale(GMtxtfield);
        btnEnable();
    }//GEN-LAST:event_gmAttachActionPerformed

    private void torAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torAttachActionPerformed
        imgSetScale(TORtxtfield);
        btnEnable();
    }//GEN-LAST:event_torAttachActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try {
            String rCard = RCtxtfield.getText();
            String f137 = F137txtfield.getText();
            String bCert = BCtxtfield.getText();
            String gMoral = GMtxtfield.getText();
            String tRecords = TORtxtfield.getText();
            String eNum = hiddenPRI.getText();

            conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            ps = conn.prepareStatement("INSERT INTO requirements"
                    + "(ReportCard,Form137,BirthCertificate,GoodMoral,TranscriptOfRecords,e_num)"
                    + "VALUES(?,?,?,?,?,?)");

            ps.setString(1, rCard);
            ps.setString(2, f137);
            ps.setString(3, bCert);
            ps.setString(4, gMoral);
            ps.setString(5, tRecords);
            ps.setString(6, eNum);

            if (ps.executeUpdate() != 0) {
                JOptionPane.showMessageDialog(null, "Thank You For Enrolling!");
                JOptionPane.showMessageDialog(null, "Please Wait For Our Evaluation!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Error! Failed to add to our database!");
            }
        } catch (Exception e) {
            Logger.getLogger(EnrollmentForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrollmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrollmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrollmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrollmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollmentForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BCtxtfield;
    private javax.swing.JLabel BG;
    private javax.swing.JTextField F137txtfield;
    private javax.swing.JTextField GMtxtfield;
    private javax.swing.JTextField RCtxtfield;
    private javax.swing.JTextField TORtxtfield;
    private javax.swing.JButton bcAttach;
    private javax.swing.JLabel bcText;
    private javax.swing.JButton f137Attach;
    private javax.swing.JLabel f137Text;
    private javax.swing.JPanel fillUpForm;
    private javax.swing.JButton gmAttach;
    private javax.swing.JLabel gmText;
    private javax.swing.JLabel headEF1;
    private javax.swing.JLabel headEF2;
    public static javax.swing.JLabel hiddenPRI;
    private javax.swing.JLabel imageDisplay;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton rcAttach;
    private javax.swing.JLabel rcText;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton torAttach;
    private javax.swing.JLabel torText;
    // End of variables declaration//GEN-END:variables
}
