/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import java.awt.*; // uses Image
import java.sql.*; // uses DriverManager and SQLException
import java.util.Vector;
import javax.swing.*; // ImageIcon, JLabel, and JOptionPane
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sevhe
 */
public class ForgotPassForm extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassForm
     */
    private static final String URL = "jdbc:mysql://localhost:3306/enrollmentsystem?allowPublicKeyRetrieval=true&useSSL=false";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "@theHouseof25";

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rset = null;
    int q, i, enumb, deleteItem;
    DefaultTableModel RecordTable;
    ResultSetMetaData rsmData;
    Vector columnData;

    public ForgotPassForm() {
        initComponents();

        resetPass.setEchoChar('✦');
        cresetPass.setEchoChar('✦');

        imageCaller();
    }

    public void imageScale(String link, JLabel label) {
        ImageIcon iconLOGO1 = new ImageIcon("C:/Users/daxxtropezz/Documents/NetBeansProjects/EnrollmentSystem/src/enrollmentsystem" + link);
        Image imgLOGO1 = iconLOGO1.getImage();
        Image imgScaleLOGO1 = imgLOGO1.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconLOGO1 = new ImageIcon(imgScaleLOGO1);
        label.setIcon(scaledIconLOGO1);
    }

    public void imageCaller() {
        String[] link
                = {"/Images/jcvhsHlLogin.jpg",
                    "/Images/newLogo.png",
                    "/Images/LionsRoarASH.png",
                    "/Images/lionTag.jpg",
                    "/Images/lionWhite.png",
                    "/Images/lion1.png",
                    "/Images/newBg.jpg"};

        imageScale(link[6], bg);
        imageScale(link[4], bgLogo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        rpUser = new javax.swing.JTextField();
        HeadRP = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        disposeBtn = new javax.swing.JButton();
        showPass = new javax.swing.JCheckBox();
        resetPass = new javax.swing.JPasswordField();
        npassLabel = new javax.swing.JLabel();
        cnpassLabel = new javax.swing.JLabel();
        showCPass = new javax.swing.JCheckBox();
        cresetPass = new javax.swing.JPasswordField();
        bgLogo = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLabel.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("USERNAME: ");
        getContentPane().add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 30));

        rpUser.setBackground(new java.awt.Color(255, 255, 255));
        rpUser.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rpUser.setForeground(new java.awt.Color(0, 0, 0));
        rpUser.setText("enter your username!");
        rpUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rpUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rpUserFocusLost(evt);
            }
        });
        getContentPane().add(rpUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 230, 30));

        HeadRP.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        HeadRP.setForeground(new java.awt.Color(255, 255, 255));
        HeadRP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadRP.setText("RESET PASSWORD");
        getContentPane().add(HeadRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 540, -1));

        submitBtn.setBackground(new java.awt.Color(51, 51, 51));
        submitBtn.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, 30));

        disposeBtn.setBackground(new java.awt.Color(51, 51, 51));
        disposeBtn.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        disposeBtn.setForeground(new java.awt.Color(255, 255, 255));
        disposeBtn.setText("CLOSE");
        disposeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disposeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(disposeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 80, 30));

        showPass.setBackground(new java.awt.Color(255, 255, 204));
        showPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        getContentPane().add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, 30));

        resetPass.setBackground(new java.awt.Color(255, 255, 255));
        resetPass.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        resetPass.setForeground(new java.awt.Color(0, 0, 0));
        resetPass.setText("⠀⠀⠀⠀⠀⠀⠀⠀");
        resetPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resetPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                resetPassFocusLost(evt);
            }
        });
        getContentPane().add(resetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 230, 30));

        npassLabel.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        npassLabel.setForeground(new java.awt.Color(255, 255, 255));
        npassLabel.setText("NEW PASSWORD: ");
        getContentPane().add(npassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        cnpassLabel.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        cnpassLabel.setForeground(new java.awt.Color(255, 255, 255));
        cnpassLabel.setText("CONFIRM NEW PASSWORD: ");
        getContentPane().add(cnpassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        showCPass.setBackground(new java.awt.Color(255, 255, 204));
        showCPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showCPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCPassActionPerformed(evt);
            }
        });
        getContentPane().add(showCPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, 30));

        cresetPass.setBackground(new java.awt.Color(255, 255, 255));
        cresetPass.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cresetPass.setForeground(new java.awt.Color(0, 0, 0));
        cresetPass.setText("⠀⠀⠀⠀⠀⠀⠀⠀");
        cresetPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cresetPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cresetPassFocusLost(evt);
            }
        });
        getContentPane().add(cresetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 230, 30));
        getContentPane().add(bgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 240, 230));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Images/newBg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void disposeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disposeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_disposeBtnActionPerformed

    private void resetPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resetPassFocusGained
        String password = String.valueOf(resetPass.getPassword());

        if (password.trim().toLowerCase().equals("⠀⠀⠀⠀⠀⠀⠀⠀")) {
            resetPass.setText("");
        }
    }//GEN-LAST:event_resetPassFocusGained

    private void resetPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resetPassFocusLost
        String password = String.valueOf(resetPass.getPassword());

        if (password.trim().equals("") || password.trim().toLowerCase().equals("⠀⠀⠀⠀⠀⠀⠀⠀")) {
            resetPass.setText("⠀⠀⠀⠀⠀⠀⠀⠀");
        }
    }//GEN-LAST:event_resetPassFocusLost

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        if (showPass.isSelected()) {
            resetPass.setEchoChar((char) 0);
        } else {
            resetPass.setEchoChar('✦');
        }
    }//GEN-LAST:event_showPassActionPerformed

    private void cresetPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cresetPassFocusGained
        String password = String.valueOf(cresetPass.getPassword());

        if (password.trim().toLowerCase().equals("⠀⠀⠀⠀⠀⠀⠀⠀")) {
            cresetPass.setText("");
        }
    }//GEN-LAST:event_cresetPassFocusGained

    private void cresetPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cresetPassFocusLost
        String password = String.valueOf(cresetPass.getPassword());

        if (password.trim().equals("") || password.trim().toLowerCase().equals("⠀⠀⠀⠀⠀⠀⠀⠀")) {
            cresetPass.setText("⠀⠀⠀⠀⠀⠀⠀⠀");
        }
    }//GEN-LAST:event_cresetPassFocusLost

    private void showCPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCPassActionPerformed
        if (showCPass.isSelected()) {
            cresetPass.setEchoChar((char) 0);
        } else {
            cresetPass.setEchoChar('✦');
        }
    }//GEN-LAST:event_showCPassActionPerformed

    private void rpUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rpUserFocusGained

        if (rpUser.getText().trim().toLowerCase().equals("enter your username!")) {
            rpUser.setText("");
        }
    }//GEN-LAST:event_rpUserFocusGained

    private void rpUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rpUserFocusLost
        if (rpUser.getText().trim().equals("")
                || rpUser.getText().trim().toLowerCase().equals("enter your username!")) {
            rpUser.setText("enter your username!");
        }
    }//GEN-LAST:event_rpUserFocusLost

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if (verifyFields()) {
            try {
                String curUser = rpUser.getText();
                String newPass = resetPass.getText();

                conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
                ps = conn.prepareStatement("UPDATE account              "
                        + "SET                         "
                        + "a_pass = ?                  "
                        + "WHERE a_user = ?            ");

                ps.setString(1, newPass);
                ps.setString(2, curUser);

                int c = ps.executeUpdate();
                if (c != 0) {
                    JOptionPane.showMessageDialog(this, "You can now login to the system!", "Password Updated!", 1);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Username does not exist!");
                }

            } catch (SQLException e) {
                java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    public boolean verifyFields() {
        String username = rpUser.getText();
        String password = String.valueOf(resetPass.getPassword());
        String confirmpassword = String.valueOf(cresetPass.getPassword());

        // checking if the fields are empty
        if (username.trim().equals("")
                || password.trim().equals("⠀⠀⠀⠀⠀⠀⠀⠀")
                || confirmpassword.trim().equals("⠀⠀⠀⠀⠀⠀⠀⠀")) {
            JOptionPane.showMessageDialog(null, "One or more fields are empty!", "Empty Fields", 2);
            return false;
        } else if (!password.equals(confirmpassword)) //check if password and password confirmation are equal
        {
            JOptionPane.showMessageDialog(null, "Passwords doesn't match!", "Confirm password!", 2);
            return false;
        } else // if everything is fine
        {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadRP;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bgLogo;
    private javax.swing.JLabel cnpassLabel;
    private javax.swing.JPasswordField cresetPass;
    private javax.swing.JButton disposeBtn;
    private javax.swing.JLabel npassLabel;
    private javax.swing.JPasswordField resetPass;
    public static javax.swing.JTextField rpUser;
    private javax.swing.JCheckBox showCPass;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
