/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import java.sql.*; // uses Connection DriverManager PreparedStatement ResultSet ResultSetMetaData
import java.util.Vector;
import javax.swing.*; // uses JOptionPane
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sevhe
 */
public class TeacherDetailsForm extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/enrollmentsystem?allowPublicKeyRetrieval=true&useSSL=false";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "@theHouseof25";

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rset = null;
    int q, i, enumb, deleteItem;
    DefaultTableModel RecordTable;
    ResultSetMetaData rsmData;
    Vector columnData;

    /**
     * Creates new form TeacherDetailsForm
     */
    public TeacherDetailsForm() {
        initComponents();
        tName.setEditable(false);
        tMail.setEditable(false);
        tContact.setEditable(false);
        tSex.setEditable(false);
        tBDate.setEditable(false);
    }

    public void teachersSubject() {
        try {
            conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            ps = conn.prepareStatement("SELECT * FROM schedule WHERE s_teacher = ?");

            ps.setString(1, tName.getText());

            rset = ps.executeQuery();
            rsmData = rset.getMetaData();

            q = rsmData.getColumnCount();

            RecordTable = (DefaultTableModel) schedTbl.getModel();
            RecordTable.setRowCount(0);

            while (rset.next()) {
                columnData = new Vector();

                for (i = 1; i <= q; i++) {
                    columnData.add(rset.getString("s_code"));
                    columnData.add(rset.getString("s_subject"));
                    columnData.add(rset.getString("s_description"));
                    columnData.add(rset.getString("s_day"));
                }
                RecordTable.addRow(columnData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teachersPanel = new javax.swing.JPanel();
        tImg = new javax.swing.JLabel();
        lblBDate = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        schedTblScrollPane = new javax.swing.JScrollPane();
        schedTbl = new javax.swing.JTable();
        tClose = new javax.swing.JButton();
        tMail = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        tBDate = new javax.swing.JTextField();
        tContact = new javax.swing.JTextField();
        tSex = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teachersPanel.setBackground(new java.awt.Color(25, 25, 25));
        teachersPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 177, 0), 2));
        teachersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 177, 0), 2));
        tImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        teachersPanel.add(tImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 125, 125));

        lblBDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBDate.setForeground(new java.awt.Color(255, 255, 255));
        lblBDate.setText("Birthdate:");
        teachersPanel.add(lblBDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, 30));

        lblName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");
        teachersPanel.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 30));

        lblEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");
        teachersPanel.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 30));

        lblContact.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContact.setForeground(new java.awt.Color(255, 255, 255));
        lblContact.setText("Contact #:");
        teachersPanel.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 30));

        lblSex.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSex.setForeground(new java.awt.Color(255, 255, 255));
        lblSex.setText("Sex:");
        teachersPanel.add(lblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 30));

        schedTblScrollPane.setBackground(new java.awt.Color(0, 0, 0));

        schedTbl.setBackground(new java.awt.Color(62, 12, 12));
        schedTbl.setForeground(new java.awt.Color(255, 255, 255));
        schedTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Schedule Code", "Subject", "Description", "Day"
            }
        ));
        schedTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schedTblMouseClicked(evt);
            }
        });
        schedTblScrollPane.setViewportView(schedTbl);

        teachersPanel.add(schedTblScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 540, 90));

        tClose.setBackground(new java.awt.Color(25, 25, 25));
        tClose.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tClose.setForeground(new java.awt.Color(255, 177, 0));
        tClose.setText("CLOSE");
        tClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 177, 0), 2));
        tClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCloseActionPerformed(evt);
            }
        });
        teachersPanel.add(tClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 90, 30));

        tMail.setBackground(new java.awt.Color(62, 12, 12));
        tMail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tMail.setForeground(new java.awt.Color(255, 255, 255));
        tMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tMail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 177, 0)));
        teachersPanel.add(tMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 290, 30));

        tName.setBackground(new java.awt.Color(62, 12, 12));
        tName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tName.setForeground(new java.awt.Color(255, 255, 255));
        tName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 177, 0)));
        teachersPanel.add(tName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 290, 30));

        tBDate.setBackground(new java.awt.Color(62, 12, 12));
        tBDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tBDate.setForeground(new java.awt.Color(255, 255, 255));
        tBDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tBDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 177, 0)));
        teachersPanel.add(tBDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 290, 30));

        tContact.setBackground(new java.awt.Color(62, 12, 12));
        tContact.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tContact.setForeground(new java.awt.Color(255, 255, 255));
        tContact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 177, 0)));
        teachersPanel.add(tContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 290, 30));

        tSex.setBackground(new java.awt.Color(62, 12, 12));
        tSex.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tSex.setForeground(new java.awt.Color(255, 255, 255));
        tSex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tSex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 177, 0)));
        teachersPanel.add(tSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 290, 30));

        getContentPane().add(teachersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        teachersSubject();
    }//GEN-LAST:event_formWindowActivated

    private void tCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_tCloseActionPerformed

    private void schedTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedTblMouseClicked
        RecordTable = (DefaultTableModel) schedTbl.getModel();
        int SelectedRows = schedTbl.getSelectedRow();

        subjectDetailsForm sdf = new subjectDetailsForm();

        String subject = (RecordTable.getValueAt(SelectedRows, 1).toString());

        try {
            conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            ps = conn.prepareStatement("SELECT * FROM schedule WHERE s_subject = ?");

            ps.setString(1, subject);

            rset = ps.executeQuery();

            if (rset.next()) {
                String teacher = rset.getString("s_teacher");
                String day = rset.getString("s_day");
                String start = rset.getString("s_starttime");
                String end = rset.getString("s_endtime");
                String description = rset.getString("s_description");

                subjectDetailsForm.subNameDET.setText(subject);
                subjectDetailsForm.teachDET.setText(teacher);
                subjectDetailsForm.dayDET.setText(day);
                subjectDetailsForm.startDET.setText(start);
                subjectDetailsForm.endDET.setText(end);
                subjectDetailsForm.descDET.setText(description);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        sdf.setVisible(true);
        sdf.setLocationRelativeTo(null);
        sdf.pack();
    }//GEN-LAST:event_schedTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBDate;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSex;
    private javax.swing.JTable schedTbl;
    private javax.swing.JScrollPane schedTblScrollPane;
    public static javax.swing.JTextField tBDate;
    private javax.swing.JButton tClose;
    public static javax.swing.JTextField tContact;
    public static javax.swing.JLabel tImg;
    public static javax.swing.JTextField tMail;
    public static javax.swing.JTextField tName;
    public static javax.swing.JTextField tSex;
    private javax.swing.JPanel teachersPanel;
    // End of variables declaration//GEN-END:variables
}
